# Generated by Django 3.1.7 on 2021-02-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='no_of_reads',
            field=models.IntegerField(default=0),
        ),
    ]
