# Generated by Django 3.1.7 on 2021-02-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_no_of_reads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='data',
            new_name='date',
        ),
    ]
