# Generated by Django 3.1.7 on 2021-02-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210226_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='brief_content',
            field=models.TextField(default="A brief (Old French from Latin 'brevis', short) is a written legal document used in various legal adversarial systems that is presented to a court arguing why one party to a particular case should prevail."),
        ),
    ]
