# Generated by Django 3.1.7 on 2021-03-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articles_brief_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='brief_content',
            field=models.TextField(default="A brief (Old French from Latin 'brevis', short) is a written legal document used in various legal adversarial systems that is presented to a court arguing why one party to a particular case should prevail...."),
        ),
        migrations.AlterField(
            model_name='articles',
            name='no_of_reads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
