# Generated by Django 3.1.7 on 2021-03-10 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0011_auto_20210310_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='starred_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
