# Generated by Django 3.1.7 on 2021-03-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20210310_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='brief_content',
            field=models.TextField(default="A brief (Old French from Latin 'brevis', short) is a written legal document used in various legal adversarial systems that is presented to a court arguing why one party to a particular case should prevail"),
        ),
    ]
